[theme]
# "Sunset Session" Color Palette (Dark Mode Version)
primaryColor = "#FF7D5A"      # Sunset Orange
backgroundColor = "#1E2128"  # Dark background
secondaryBackgroundColor = "#2B3A67" # Dusk Blue (for cards)
textColor = "#FFFFFF"          # White text
font = "sans serif"